// <auto-generated />
using AdTorrBot.BotTelegram.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdTorrBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241119015231_1245")]
    partial class _1245
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AdTorrBot.BotTelegram.Db.Model.SettingsBot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdChat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeZoneOffset")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SettingsBot");
                });

            modelBuilder.Entity("AdTorrBot.BotTelegram.Db.Model.SettingsTorrserverBot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActiveAutoChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeAutoChangePassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("idChat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingsTorrserverBot");
                });

            modelBuilder.Entity("AdTorrBot.BotTelegram.Db.Model.TextInputFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagLogin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagPassword")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettCacheSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettConnectionsLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettDownloadRateLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettFriendlyName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettPeersListenPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettPreloadCache")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettReaderReadAHead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettRetrackersMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettSslCert")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettSslKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettSslPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettTorrentDisconnectTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettTorrentsSavePath")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlagTorrSettUploadRateLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdChat")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTextFlagTrue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TextInputFlag");
                });

            modelBuilder.Entity("AdTorrBot.BotTelegram.Db.Model.TorrserverModel.BitTorrConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionsLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableDHT")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisablePEX")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableTCP")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableUPNP")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableUTP")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableUpload")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadRateLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDLNA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDebug")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableIPv6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableRutorSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForceEncrypt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdChat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameProfileBot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PeersListenPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreloadCache")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReaderReadAHead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RemoveCacheOnDrop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ResponsiveMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetrackersMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SslCert")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SslKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SslPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TorrentDisconnectTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TorrentsSavePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadRateLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseDisk")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdChat", "NameProfileBot")
                        .IsUnique();

                    b.ToTable("BitTorrConfig");
                });

            modelBuilder.Entity("AdTorrBot.BotTelegram.Db.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdChat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
